export const ACTION_TYPE = {
    SET_LOADING: 'SET_LOADING',
    SET_TODOS: 'SET_TODOS',
    SET_ERROR: 'SET_ERROR',
    ADD_OPTIMISTIC_TODO: 'ADD_OPTIMISTIC_TODO',
    DELETE_OPTOMOSTIC_TODO: 'DELETE_OPTOMOSTIC_TODO',
    RESTORE_TODO: 'RESTORE_TODO',
    EDIT_OPTIMISTIC_TODO: 'EDIT_OPTIMISTIC_TODO',
    TOGGLE_OPTIMISTIC_TODO: 'TOGGLE_OPTIMISTIC_TODO',
    SET_SEARCH_TERM: 'SET_SEARCH_TERM',
    SET_SORT_ENABLED: 'SET_SORT_ENABLED',
    SET_SORT_ORDER: 'SET_SORT_ORDER',
    SET_DEBOUNCED_SEARCH: 'SET_DEBOUNCED_SEARCH'
}